name: Deploy to Amazon Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to Lightsail
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: 22
        source: "."
        target: "/bitnami/wordpress/wp-content/themes/digitalresume"

    - name: SSH commands
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/bitnami/wordpress
          # any additional commands like changing permissions